### ISSUE TITLE
Unnecessary add + remove of 'new issue' label for trop backports

### ISSUE THREAD

**Issue by ckerr** [electron/cation#8]
The flow between trop & cation [here](https://github.com/electron/electron/pull/17215) seems weird. It all works out in the end though so maybe the add + remove is intentional?

**Comment by MarshallOfSound** [comment]
It's not too bad at the moment as it does self-correct quite quickly, the issue here is the race between the `backport` label being applied and `cation` processing the incoming webhook.

We are supposed to handle this by checking the PR title for the word "backport" here https://github.com/electron/cation/blob/master/src/24-hour-rule/index.ts#L18-L19 but that doesn't appear to be working

**Comment by MarshallOfSound** [comment]
Or the more reasonable option, we hadn't deployed that code 😆 I've run the deploy so this shouldn't happen any more 👍
